version: "2"

services:
  app:
    build: .
    restart: unless-stopped
    environment:
      - VERSION=${VERSION}
      - DEVELOPER_MODE=${DEVELOPER_MODE}
      - BOT_TOKEN=${BOT_TOKEN}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - DAILY_STORE_URL=${DAILY_STORE_URL}
      - FORTNITE_STATUS_URL=${FORTNITE_STATUS_URL}
      - FORTNITE_NEWS_URL=${FORTNITE_NEWS_URL}
    depends_on:
      - redis

  redis:
    image: redis:5.0.3-alpine
    restart: unless-stopped
    volumes:
      - redis-data:/data

networks:
  default:

volumes:
  redis-data:
