version: "2"

services:
  app:
    build: .
    restart: unless-stopped
    environment:
      - VERSION=${VERSION}
      - DEVELOPER_MODE=${DEVELOPER_MODE}
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
      - BOT_TOKEN=${BOT_TOKEN}
      - CHANNEL_ID=${CHANNEL_ID}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    depends_on:
      - redis

  redis:
    image: redis:5.0.3-alpine
    restart: unless-stopped
    volumes:
      - redis-data:/data

networks:
  default:

volumes:
  redis-data:
